### PR TITLE
Port from GObject from GLib

### PR DESCRIPTION
**Pull request by aryanharitsh123**
made some changes,working fine.

### CODE REVIEW

**Comment by chimosky** [comment]
Reviewed, thanks.

Kindly complete the port as there are still instances of `GObject` that need to be ported to `GLib`.

**Comment by aryanharitsh123** [comment]
I know that there are some. but when I ported them, the activity was showed "Failed To start".

**Comment by Hrishi1999** [comment]
Please debug it. What do the logs say?

**Comment by aryanharitsh123** [comment]
Review.

**Comment by chimosky** [comment]
@aryanharitsh123 please squash into a single commit.

**Comment by aryanharitsh123** [comment]
Ok

**Comment by chimosky** [comment]
@aryanharitsh123 please let the commits only be the ones authored by you.

**Comment by pro-panda** [comment]
Also please update your commit message. 
Writing `few changes` in the commit message details doesn't provide any useful information to other developers

**Comment by aryanharitsh123** [comment]
@chimosky Please Review

**Comment by pro-panda** [comment]
Thanks. Reviewed.
Since there are other reviewers involved, I'll hold up for others to review

**Comment by chimosky** [comment]
Reviewed. Thanks.

**Comment by pro-panda** [comment]
@quozl I'll volunteer for https://github.com/sugarlabs/PolariActivity

**Pull request merged**
