### PR TITLE
Port to Python3

### LINKED ISSUE #14: Port to Python 3.

### PR DESCRIPTION
**Pull request by srevinsaju**
Fixes #14 

Testing in progress 
Based on top of @chimosky on #15 

Those who are interested to test, please let me know of the bugs, so that it could be merged faster

### CODE REVIEW

**Comment by srevinsaju** [comment]
Some new features : 
**OLD** : 
image

**NEW**:
image

**Comment by srevinsaju** [comment]
Hands up for new features
A solution to my sore eyes:
image

**Features++** (not yet committed, under testing)
* Dark Mode (inherited from Terminal-activity)
* Zoom / Increase / Decrease Font Size

**Comment by srevinsaju** [comment]
I guess I am done
There are stuff in the logs which I am aware of, but I am not sure if the regression which happened after the port, maybe @chimosky might be able to tell. 

So far, there are no `Tracebacks` in the logs. Please let me know, if you get `Tracebacks`. I am however not sure of the _handled error_ in purk which was done by Ignacio 5 years ago

Detailed Features
* Port to Python3
* Dark theme / Light theme (theme selector)
* Font size (Zoom in / Zoom out)
* better tab appearance (increased padding)

Please review; Let me know of any changes I can make

**Comment by chimosky** [comment]
Moved to #17.

**Pull request closed without merging**
